// AUTO-GENERATED by src/server/api/icons/index.get.ts - do not edit

import type { BxIconName } from './bx.types';
import type { CarbonIconName } from './carbon.types';
import type { Fa6RegularIconName } from './fa6-regular.types';
import type { Fa6SolidIconName } from './fa6-solid.types';
import type { GameIconsIconName } from './game-icons.types';
import type { HeroiconsIconName } from './heroicons.types';
import type { LucideIconName } from './lucide.types';
import type { MdiIconName } from './mdi.types';
import type { PhIconName } from './ph.types';
import type { RiIconName } from './ri.types';
import type { TablerIconName } from './tabler.types';

export type IconName
  = BxIconName
    | CarbonIconName
    | Fa6RegularIconName
    | Fa6SolidIconName
    | GameIconsIconName
    | HeroiconsIconName
    | LucideIconName
    | MdiIconName
    | PhIconName
    | RiIconName
    | TablerIconName
    | '';
