import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

type PackageJson = {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
};

const require = createRequire(import.meta.url);
const scriptDir = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(scriptDir, '..');
const packageJsonPath = join(rootDir, 'package.json');
const outDirPath = join(rootDir, 'src', 'app', 'types', 'icons');

function readPackageJson() {
  const raw = readFileSync(packageJsonPath, 'utf8');
  return JSON.parse(raw) as PackageJson;
}

function getIconifyPackageNames(packageJson: PackageJson) {
  const mergedDependencies = {
    ...(packageJson.dependencies ?? {}),
    ...(packageJson.devDependencies ?? {}),
  };

  return Object.keys(mergedDependencies).filter((packageName) => packageName.startsWith('@iconify-json/'));
}

function toTypeName(prefix: string) {
  return `${prefix
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('')}IconName`;
}

function clearGeneratedFiles(directoryPath: string) {
  mkdirSync(directoryPath, { recursive: true, });

  for (const fileName of readdirSync(directoryPath)) {
    if (fileName.endsWith('.types.ts') || fileName === 'index.ts')
      rmSync(join(directoryPath, fileName));
  }
}

function writeSetTypeFile(packageName: string) {
  const setData = require(`${packageName}/icons.json`);
  const prefix = setData.prefix as string;
  const typeName = toTypeName(prefix);
  const iconNames = Object.keys(setData.icons ?? {}).sort();
  const fileContent = [
    '// AUTO-GENERATED by scripts/get-icon-names.ts - do not edit',
    '',
    `export type ${typeName}`,
    ...iconNames.map((iconName, index) => `${index === 0
      ? '  = '
      : '    '}| '${prefix}:${iconName}'`),
    ';',
    '',
  ].join('\n');

  writeFileSync(join(outDirPath, `${prefix}.types.ts`), fileContent, 'utf8');

  return {
    prefix,
    typeName,
    count: iconNames.length,
  };
}

function writeIndexFile(typeNamesByPrefix: Array<{ prefix: string; typeName: string }>) {
  const fileContent = [
    '// AUTO-GENERATED by scripts/get-icon-names.ts - do not edit',
    '',
    ...typeNamesByPrefix.map(({ prefix, typeName, }) => `import type { ${typeName} } from './${prefix}.types';`),
    '',
    'export type IconName',
    ...typeNamesByPrefix.map(({ typeName, }, index) => `${index === 0
      ? '  = '
      : '    '}| ${typeName}`),
    '    | \'\';',
    '',
  ].join('\n');

  writeFileSync(join(outDirPath, 'index.ts'), fileContent, 'utf8');
}

function main() {
  const packageJson = readPackageJson();
  const packageNames = getIconifyPackageNames(packageJson);

  if (packageNames.length === 0)
    throw new Error('package.json 에서 @iconify-json/* 패키지를 찾지 못했습니다.');

  clearGeneratedFiles(outDirPath);

  const generatedSets = packageNames.map(writeSetTypeFile);
  writeIndexFile(generatedSets);

  const totalIconCount = generatedSets.reduce((sum, item) => sum + item.count, 0);

  console.log(`아이콘 타입 파일 ${generatedSets.length}개 세트, 총 ${totalIconCount}개 항목을 생성했습니다.`);
}

try {
  main();
}
catch (error) {
  console.error('아이콘 타입 파일 생성 중 오류가 발생했습니다.');
  console.error(error);
  process.exitCode = 1;
}
