import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join } from 'node:path';

const PACKAGES = [
  '@iconify-json/bx',
  '@iconify-json/carbon',
  '@iconify-json/fa6-regular',
  '@iconify-json/fa6-solid',
  '@iconify-json/game-icons',
  '@iconify-json/heroicons',
  '@iconify-json/lucide',
  '@iconify-json/mdi',
  '@iconify-json/ph',
  '@iconify-json/ri',
  '@iconify-json/tabler',
] as const;

function toTypeName(prefix: string) {
  return `${prefix
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('')}IconName`;
}

export default defineEventHandler(async () => {
  try {
    const require = createRequire(import.meta.url);
    const outDirPath = join(process.cwd(), 'src/app/types/icons');
    mkdirSync(outDirPath, { recursive: true, });

    for (const fileName of readdirSync(outDirPath)) {
      if (fileName.endsWith('.types.ts') || fileName === 'index.ts')
        rmSync(join(outDirPath, fileName));
    }

    const unionTypeNames: string[] = [];
    const importTypeNames: string[] = [];

    for (const packageName of PACKAGES) {
      const setData = require(`${packageName}/icons.json`);
      const prefix = setData.prefix as string;
      const typeName = toTypeName(prefix);
      const iconNames = Object.keys(setData.icons ?? {}).sort();
      const fileLines: string[] = [
        '// AUTO-GENERATED by src/server/api/icons/index.get.ts - do not edit',
        '',
        `export type ${typeName} =`,
        ...iconNames.map((iconName) => `  | '${prefix}:${iconName}'`),
        ';',
        '',
      ];

      writeFileSync(
        join(outDirPath, `${prefix}.types.ts`),
        fileLines.join('\n'),
        'utf8'
      );

      unionTypeNames.push(typeName);
      importTypeNames.push(`import type { ${typeName} } from './${prefix}.types';`);
    }

    const indexLines = [
      '// AUTO-GENERATED by src/server/api/icons/index.get.ts - do not edit',
      '',
      ...importTypeNames,
      '',
      `export type IconName = ${unionTypeNames.join(' | ')};`,
      '',
    ];

    writeFileSync(join(outDirPath, 'index.ts'), indexLines.join('\n'), 'utf8');

    return {
      error: false,
      message: '아이콘 이름 타입 데이터가 생성되었습니다.',
    };
  }
  catch (error) {
    console.error(error);
    return {
      error: true,
      message: '아이콘 이름 데이터 생성 중 오류가 발생했습니다.',
    };
  }
});
